### ISSUE TITLE
1.2.2.0 not working on Mac

### ISSUE THREAD

**Issue by dpeckham** [rgleason/polar_pi#13]
OpenCPN 5.8.0-0 from official site. MacOS Ventura 13.3.1 (22E261) on M2 MacBook Air. Plugin is installed and enabled, but the button/icon does not appear in the Toolbar.

**Comment by rgleason** [comment]
https://github.com/rgleason/polar_pi/pull/14/commits/32730fa8ccbd8bf2811b331d52b801bba5ba0f1b

**Comment by rgleason** [comment]
@dpeckham   Can't this be closed now?
