### ISSUE TITLE
Streamline + libs

### ISSUE THREAD

**Issue by rgleason** [rgleason/polar_pi#17]
I've gotten Polar_pi working/building with the original nmea0183 library that was located in src/nmea
I am trying to use the standard  libs/nmea0183  which appears to be very similar.
I have changed some file references at the top in polar.h and polardialog.h  to fix some errors, and that has corrected that problem.
Now there is another pesky issue in the output.txt file after running a clean build that fails, I get.

```
  icons.cpp
C:\Users\fcgle\source\polar_pi\src\Polar.h(99,19): error C3646: 'm_NMEA0183': unknown override specifier (compiling source file C:\Users\fcgle\source\polar_pi\src\PolarGui.cpp) [C:\Users\fcgle\source\polar_pi\build\polar_pi.vcxproj]
C:\Users\fcgle\source\polar_pi\src\Polar.h(99,29): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file C:\Users\fcgle\source\polar_pi\src\PolarGui.cpp) [C:\Users\fcgle\source\polar_pi\build\polar_pi.vcxproj]
C:\Users\fcgle\source\polar_pi\src\Polar.h(99,19): error C3646: 'm_NMEA0183': unknown override specifier (compiling source file C:\Users\fcgle\source\polar_pi\src\PolarDialog.cpp) [C:\Users\fcgle\source\polar_pi\build\polar_pi.vcxproj]

```

Polar.h shows this

```
private:
	PolarDialog*	dlg;
	FilterDlg*		filterDlg;

	NMEA0183P       	m_NMEA0183;   <----LINE 99

	wxString		logbookDataPath;
	wxSize			center;
	int				rSpeed[24];
	double			dist;

	double toRad(int angle);
	void   loadVDR();
//	void calculateData();
```

How do I fix this problem?

**Comment by rgleason** [comment]
I did a search on all src files for m_NMEA0183

Search "m_NMEA0183" (28 hits in 2 files of 76 searched)
  C:\Users\fcgle\source\polar_pi\src\Polar.cpp (27 hits)
	Line 1348:     m_NMEA0183 << sentence;
	Line 1350:     if ( m_NMEA0183.PreParse() )
	Line 1352:         if ( m_NMEA0183.LastSentenceIDReceived == _T( "RMC" ) )
	Line 1354:             if ( m_NMEA0183.Parse() )
	Line 1355:                 if ( m_NMEA0183.Rmc.SpeedOverGroundKnots != 999.0 )
	Line 1356:                     gpsSpeed = m_NMEA0183.Rmc.SpeedOverGroundKnots;
	Line 1359:         else if ( m_NMEA0183.LastSentenceIDReceived == _T( "VHW" ) )
	Line 1361:             if ( m_NMEA0183.Parse() )
	Line 1362:                 speedoSpeed = m_NMEA0183.Vhw.Knots;
	Line 1364:         else if ( m_NMEA0183.LastSentenceIDReceived == _T( "MWV" ) )
	Line 1366:             if ( m_NMEA0183.Parse() )
	Line 1368:                 windAngle = m_NMEA0183.Mwv.WindAngle;
	Line 1369:                 windReference = m_NMEA0183.Mwv.Reference;
	Line 1371:                 if ( m_NMEA0183.Mwv.WindSpeedUnits == 'K' )
	Line 1372:                     windSpeed = wxRound( m_NMEA0183.Mwv.WindSpeed/1.852 );
	Line 1373:                 else if ( m_NMEA0183.Mwv.WindSpeedUnits == 'M' )
	Line 1374:                     windSpeed = wxRound( ( m_NMEA0183.Mwv.WindSpeed*3600 )/1852 );
	Line 1375:                 else if ( m_NMEA0183.Mwv.WindSpeedUnits == 'N' )
	Line 1376:                     windSpeed = m_NMEA0183.Mwv.WindSpeed;
	Line 1380:         else if ( m_NMEA0183.LastSentenceIDReceived == _T( "VWR" ) )
	Line 1382:             if ( m_NMEA0183.Parse() )
	Line 1384:                 windAngle = m_NMEA0183.Vwr.WindDirectionMagnitude;
	Line 1386:                 windSpeed = m_NMEA0183.Vwr.WindSpeedKnots;
	Line 1390:         else if ( m_NMEA0183.LastSentenceIDReceived == _T( "VWT" ) )
	Line 1392:             if ( m_NMEA0183.Parse() )
	Line 1394:                 windAngle = m_NMEA0183.Vwt.WindDirectionMagnitude;
	Line 1396:                 windSpeed = m_NMEA0183.Vwt.WindSpeedKnots;
  C:\Users\fcgle\source\polar_pi\src\Polar.h (1 hit)
	Line  99: 	NMEA0183P       	m_NMEA0183;

**Comment by rgleason** [comment]
I think I've fixed a few of the includes in CMakeLists.txt and the output is considerably longer but the same error comes up as above.

I am going make a commit and push this up to the streamline branch  but I will disable building.
Perhaps you can identify what needs to be done.

**Comment by rgleason** [comment]
Here is Polar 1.2.7.0  as it stands now.  https://github.com/rgleason/polar_pi/tree/streamline

**Comment by rgleason** [comment]
Or look at the appveyor build, line 376
https://ci.appveyor.com/project/rgleason/polar-pi/builds/48000628

**Comment by bdbcat** [comment]
Rick:
NMEA0183P       	m_NMEA0183;   <----LINE 99

I do not know what NMEA0183P is.

Try:
NMEA0183       	m_NMEA0183;

**Comment by rgleason** [comment]
That worked!   A wayward keystroke I think.

**Comment by rgleason** [comment]
Pushed to https://github.com/rgleason/polar_pi/tree/streamline
Landing in beta   https://cloudsmith.io/~opencpn/repos/polar-beta/packages/?q=1.2.8.0

**Comment by rgleason** [comment]
Here is a Progress Report
https://github.com/jongough/testplugin_pi/issues/177

**Comment by rgleason** [comment]
I think this is fixed now. Closing
