### ISSUE TITLE
Polar plugin icon appears many times and keeps multiplying in plugin toolbar when Polar plugin is enabled

### ISSUE THREAD

**Issue by mgrouch** [rgleason/polar_pi#7]
Polar plugin icon appears many times and keeps multiplying in plugin toolbar when Polar plugin is enabled

I had it on raspberry pi. Not sure about other set ups.

Thanks,
--MG

https://github.com/OpenCPN/OpenCPN/issues/2383

**Comment by rgleason** [comment]
The plugin has changed and is on a new version number.  Please try the current plugin in the PI Manager (PIM)

**Comment by rgleason** [comment]
@mgrouch have you tried the most recent version?

**Comment by rgleason** [comment]
I am closing this. It is old.
